services:
  web:
    build:
      context: .
    tty: true
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm run dev"
    ports:
      - 4000:3000
    networks:
      - ghouse_network
    env_file:
      - .env.local

  api:  # ✅ API サービス追加
    build:
      context: ./api
    ports:
      - 3001:3000
    volumes:
      - ./api:/app
    depends_on:
      - db
    networks:
      - ghouse_network
    env_file:
      - ./api/.env.local

  db:  # ✅ データベース追加（例: PostgreSQL）
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ghouse_network

networks:
  ghouse_network:
    external: true

volumes:
  db_data:
